export const funnyProjects = [
  { title: "Dad Joke Generator", slug: "dad-joke" },
  { title: "Meme Generator", slug: "meme-generator" },
  { title: "Magic 8-Ball", slug: "magic-8-ball" },
  { title: "Random Cat Viewer", slug: "random-cat" },
  { title: "Chicken Joke Machine", slug: "chicken-joke" },
  { title: "Virtual Pet Rock", slug: "pet-rock" },
  { title: "Bad UX Form", slug: "bad-form" },
  { title: "Roast Button", slug: "roast-me" },
  { title: "GIF Battle", slug: "gif-battle" },
  { title: "Emoji Translator", slug: "emoji-translator" },
  { title: "Fake Loading Screen", slug: "fake-loader" },
  { title: "Compliment Generator", slug: "compliment-gen" },
  { title: "Silly Face Distorter", slug: "face-distorter" },
  { title: "Internet Speed Faker", slug: "fake-speed-test" },
  { title: "Reverse Typing Game", slug: "reverse-typing" },
  { title: "Parrot Repeater", slug: "parrot-repeater" },
  { title: "Weird Horoscope", slug: "weird-horoscope" },
  { title: "Fake Social Feed", slug: "fake-feed" },
  { title: "Angry Button", slug: "angry-button" },
  { title: "404 Page Prank", slug: "fake-404" },
  { title: "Keyboard Sound FX", slug: "keyboard-fx" },
  { title: "Mouse Trail Sparkles", slug: "mouse-sparkles" },
  { title: "Evil Captcha", slug: "evil-captcha" },
  { title: "Overreacting Alert Box", slug: "alert-box" },
  { title: "Suspicious Cookie Clicker", slug: "cookie-clicker" },
  { title: "Rickroll Button", slug: "rickroll" },
  { title: "Drama Alert Generator", slug: "drama-alert" },
  { title: "Confetti Bomb Button", slug: "confetti-bomb" },
  { title: "Mood Swing Meter", slug: "mood-meter" },
  { title: "Dancing Emoji Party", slug: "emoji-party" },
  { title: "Broken Link Simulator", slug: "broken-link" },
  { title: "Name Your Potato", slug: "name-your-potato" },
  { title: "Random Excuse Machine", slug: "excuse-machine" },
  { title: "Fortune Cookie Reader", slug: "fortune-cookie" },
  { title: "Laugh Track App", slug: "laugh-track" },
  { title: "Sarcasm Converter", slug: "sarcasm-converter" },
  { title: "Random Button Parade", slug: "button-parade" },
  { title: "Dizzy Spinner Challenge", slug: "dizzy-spinner" },
  { title: "Alien Translator", slug: "alien-translator" },
  { title: "Self-Destruct Button", slug: "self-destruct" },
  { title: "Tiny Rage Bar", slug: "rage-bar" },
  { title: "Toilet Flush Soundboard", slug: "toilet-soundboard" },
  { title: "Scream Counter", slug: "scream-counter" },
  { title: "Slow Clap Simulator", slug: "slow-clap" },
  { title: "Instant Karma Machine", slug: "karma-machine" },
  { title: "Dance Battle Spinner", slug: "dance-spinner" },
  { title: "Cringe Detector", slug: "cringe-detector" },
  { title: "Banana Clicker", slug: "banana-clicker" },
  { title: "Echo Chamber", slug: "echo-chamber" },
  { title: "Yawn Counter", slug: "yawn-counter" },
  { title: "Overhype Button", slug: "overhype-button" },
  { title: "Random Animal Noises", slug: "animal-noises" },
  { title: "Catwalk Simulator", slug: "catwalk-simulator" },
  { title: "Awkward Silence Button", slug: "awkward-silence" },
  { title: "Laugh Until You Lose", slug: "laugh-you-lose" },
  { title: "Microwave Beep App", slug: "microwave-beep" },
  { title: "Extreme Zoom In", slug: "extreme-zoom" },
  { title: "Dramatic Chipmunk Viewer", slug: "chipmunk-viewer" },
  { title: "Guess The Noise", slug: "guess-the-noise" },
  { title: "Horrible Color Picker", slug: "bad-color-picker" },
  { title: "Nap Scheduler", slug: "nap-scheduler" },
  { title: "Alien Mood Detector", slug: "alien-mood" },
  { title: "Unicorn Tracker", slug: "unicorn-tracker" },
  { title: "Emoji Memory Game", slug: "emoji-memory" },
  { title: "Haunted Button", slug: "haunted-button" },
  { title: "Unnecessary Slider", slug: "useless-slider" },
  { title: "Infinite Scroll Troll", slug: "scroll-troll" },
  { title: "Random Snore Player", slug: "snore-player" },
  { title: "Dumb Alarm Clock", slug: "dumb-alarm" },
  { title: "Invisible Maze", slug: "invisible-maze" },
  { title: "Random OOF Generator", slug: "oof-generator" },
  { title: "Llama Translator", slug: "llama-translator" },
  { title: "Virtual Bubble Wrap", slug: "bubble-wrap" },
  { title: "Duck Scream App", slug: "duck-screamer" },
  { title: "Guess My Mood (Wrong)", slug: "guess-mood-wrong" },
  { title: "Staring Contest Game", slug: "staring-contest" },
  { title: "Tiny Text Typer", slug: "tiny-text" },
  { title: "Unsolvable Puzzle", slug: "unsolvable-puzzle" },
  { title: "Fake Blue Screen of Death", slug: "bsod-fake" },
];
